version: 0.0
os: linux
files:
  - source: html
    destination: /home/ubuntu/html

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
      runas: root
